version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11-browsers
        #auth:
        #username: fikitout
        #password: Unlimitagbero@007
    steps:
      - checkout
      - run: mkdir test-reports
      - run:
          name: Download Selenium
          command: curl -O http://selenium-release.storage.googleapis.com/3.5/selenium-server-standalone-3.5.3.jar
      - run:
          name: Start Selenium
          command: java -jar selenium-server-standalone-3.5.3.jar -log test-reports/selenium.log
          background: true
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run the application
          command: node server.js
          background: true

      #- run:
      #    name: Install Chrome Driver
      #    command: |
      #      npm install chromedriver
      #- run:
      #    name: Start Chrome Driver
      #    command: ./node_modules/chromedriver/lib/chromedriver/chromedriver
      #    background: true
      - run:
          name: Run tests
          command: npm run test
