version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:11-browsers
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm"
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run the application
          command: node server.js
          background: true
      - run:
          name: Install Chrome Driver
          command: |
            CHROME_VERSION="81.0.4044.138"
            wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb
            apt install -y /tmp/chrome.deb
            rm /tmp/chrome.deb
            wget -qP /tmp/ "https://chromedriver.storage.googleapis.com/$CHROME_VERSION/chromedriver_linux64.zip"
            sudo unzip -o /tmp/chromedriver_linux64.zip -d /usr/bin
      #- run:
      #   name: Start Chrome Driver
      #    command: ./node_modules/chromedriver/lib/chromedriver/chromedriver
      #    background: true
      - run:
          name: Run tests
          command: npm run test
